# test yaml for rinstall

---
packages:
  apt:
    utilities:
    - wget
    - curl
    - snapd
    standard:
    - timeshift
  snap:
    - golang
  custom:
    command: go install
    packages:
    - github.com/yadayad/thing.git
    