[package]
name = "rinstall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.0"
clap = "3.0.0"
linked-hash-map = "0.5.4"
serde = "1.0"
serde_yaml = "0.8"
lazy_static = "1.4.0"